site_name: SimuladorQ 
pages:
 - Introducción: index.md
 - Modelos: Modelos.md
 - Herramientas: Herramientas.md
 - Funcionamiento de SimuladorQ: FuncionamientodeSimuladorQ.md
 - Análisis del código: Análisisdelcódigo.md
 - Desarrollo de la Interfáz: DesarrolloDeLaInterfaz.md
 - Pruebas de Funcionamiento: PruebasdeFuncionamiento.md
 - Nosotros: Nosotros.md
 - Descarga: Descarga.md
 - Bibliografía: Bibliografia.md

site_description: Simulador de Colas. Proyecto Final Trafico FI-UNRC.

site_author: Ibarra, Manchado

theme: readthedocs

repo_url: https://github.com/maxxxis182/trafico

extra_javascript: [’/markdownExtension.js’,’/mermaidExtension.js’, 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML']


# the third-party extenison mdx_math.py comes with a setup.py script
markdown_extensions: 
    - math:
        enable_dollar_delimiter: True  
    - fenced_code
    - footnotes
    - toc
    - smarty
    

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
